/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CafesIndexRouteImport } from './routes/cafes.index'
import { Route as CafesCafeIdRouteImport } from './routes/cafes.$cafeId'
import { Route as InstallationsIndexRouteImport } from './routes/installations.index'
import { Route as InstallationsInstallationIdRouteImport } from './routes/installations.$installationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesIndexRoute = CafesIndexRouteImport.update({
  id: '/cafes/',
  path: '/cafes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesCafeIdRoute = CafesCafeIdRouteImport.update({
  id: '/cafes/$cafeId',
  path: '/cafes/$cafeId',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsIndexRoute = InstallationsIndexRouteImport.update({
  id: '/installations/',
  path: '/installations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsInstallationIdRoute =
  InstallationsInstallationIdRouteImport.update({
    id: '/installations/$installationId',
    path: '/installations/$installationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/installations/$installationId': typeof InstallationsInstallationIdRoute
  '/cafes/': typeof CafesIndexRoute
  '/installations/': typeof InstallationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/installations/$installationId': typeof InstallationsInstallationIdRoute
  '/cafes': typeof CafesIndexRoute
  '/installations': typeof InstallationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/installations/$installationId': typeof InstallationsInstallationIdRoute
  '/cafes/': typeof CafesIndexRoute
  '/installations/': typeof InstallationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafes/$cafeId'
    | '/installations/$installationId'
    | '/cafes/'
    | '/installations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafes/$cafeId'
    | '/installations/$installationId'
    | '/cafes'
    | '/installations'
  id:
    | '__root__'
    | '/'
    | '/cafes/$cafeId'
    | '/installations/$installationId'
    | '/cafes/'
    | '/installations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafesCafeIdRoute: typeof CafesCafeIdRoute
  InstallationsInstallationIdRoute: typeof InstallationsInstallationIdRoute
  CafesIndexRoute: typeof CafesIndexRoute
  InstallationsIndexRoute: typeof InstallationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes/': {
      id: '/cafes/'
      path: '/cafes'
      fullPath: '/cafes/'
      preLoaderRoute: typeof CafesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes/$cafeId': {
      id: '/cafes/$cafeId'
      path: '/cafes/$cafeId'
      fullPath: '/cafes/$cafeId'
      preLoaderRoute: typeof CafesCafeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/': {
      id: '/installations/'
      path: '/installations'
      fullPath: '/installations/'
      preLoaderRoute: typeof InstallationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/$installationId': {
      id: '/installations/$installationId'
      path: '/installations/$installationId'
      fullPath: '/installations/$installationId'
      preLoaderRoute: typeof InstallationsInstallationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafesCafeIdRoute: CafesCafeIdRoute,
  InstallationsInstallationIdRoute: InstallationsInstallationIdRoute,
  CafesIndexRoute: CafesIndexRoute,
  InstallationsIndexRoute: InstallationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
