/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CafesIndexRouteImport } from './routes/cafes.index'
import { Route as InstallationsIndexRouteImport } from './routes/installations.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesIndexRoute = CafesIndexRouteImport.update({
  id: '/cafes/',
  path: '/cafes/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsIndexRoute = InstallationsIndexRouteImport.update({
  id: '/installations/',
  path: '/installations/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafes/': typeof CafesIndexRoute
  '/installations/': typeof InstallationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafes': typeof CafesIndexRoute
  '/installations': typeof InstallationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cafes/': typeof CafesIndexRoute
  '/installations/': typeof InstallationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cafes/' | '/installations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cafes' | '/installations'
  id: '__root__' | '/' | '/cafes/' | '/installations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafesIndexRoute: typeof CafesIndexRoute
  InstallationsIndexRoute: typeof InstallationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes/': {
      id: '/cafes/'
      path: '/cafes'
      fullPath: '/cafes/'
      preLoaderRoute: typeof CafesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/': {
      id: '/installations/'
      path: '/installations'
      fullPath: '/installations/'
      preLoaderRoute: typeof InstallationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafesIndexRoute: CafesIndexRoute,
  InstallationsIndexRoute: InstallationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
